# Configuration for Optuna

# Execution configuration
num_envs: 8               # Number of training environments
num_eval_envs: 4          # Number of evaluation environments
random_seed: false        # Enables random seed
seed: 1297111683          # Defines seed if not randomly generated
n_trials: 100
n_eval_episodes: 5       # Number of evaluation episodes 

# Robot configuration
#robot_name: "Panda"
#robot_name: "IIWA"
robot_name: "Sawyer"
controller: "OSC_POSE"
gripper: "default"

# Algorithm configuration
#algorithm: "DDPG"
algorithm: "PPO"
#algorithm: "SAC"
policy: "MlpPolicy"
#policy: "CnnPolicy"